####################
# Settings         #
####################
path: settings
title: Settings
icon: mdi:settings
cards:
  - type: vertical-stack
    cards:
      - type: markdown                  ## Instellingen header
        content: |
         ## Instellingen
        style: |
         ha-card {
          margin: 0px 14px -5px 14px;
          box-shadow: none;
          --paper-card-background-color: rgba(0, 0, 0, 0.0)
          }
          h2 {
            font-size: 18px;
            font-weight: 400;
            padding-left: 10px;
            border-left: 3px solid rgba(81, 134, 236);
          }

      - type: horizontal-stack ### 1st row
        cards:
        - type: custom:button-card
          style: |
           ha-card {
              box-shadow: var(--card-box-shadow);
              margin: 0px 0px 0px 14px;
            }
          entity: input_boolean.enable_pir_woonkamer
          tap_action: 
            action: toggle
          name: Woonkamer
          icon: '[[[ if (entity.state == "on") return "mdi:motion-sensor"; else return "mdi:walk"; ]]]'
          show_state: false
          confirmation:
            text: '[[[ return `Weet je zeker dat je de automatische verlichting in de woonkamer wil wijzigen?` ]]]'
          styles:
            card:
              - width: 120px
              - height: 120px
            name:
              - font-size: 12px
          state:
            - value: 'off'
              styles:
                card:
                  - filter: opacity(50%)
                icon:
                  - filter: grayscale(100%)
        - type: custom:button-card
          entity: input_boolean.enable_pir_gang
          tap_action: 
            action: toggle
          name: Gang
          icon: '[[[ if (entity.state == "on") return "mdi:motion-sensor"; else return "mdi:walk"; ]]]'
          show_state: false
          confirmation:
            text: '[[[ return `Weet je zeker dat je de automatische gangverlichting wil wijzigen?` ]]]'
          styles:
            card:
              - width: 120px
              - height: 120px
            name:
              - font-size: 12px
          state:
            - value: 'off'
              styles:
                card:
                  - filter: opacity(50%)
                icon:
                  - filter: grayscale(100%)
        - type: custom:button-card
          entity: input_boolean.toon_on_movement
          name: Toon op beweging
          show_state: false
          confirmation:
            text: '[[[ return `Weet je zeker dat je de verwarming automatisch aan wil laten zetten?` ]]]'
          styles:
            card:
              - width: 120px
              - height: 120px
            name:
              - font-size: 12px
          state:
            - value: 'off'
              styles:
                card:
                  - filter: opacity(50%)
                icon:
                  - filter: grayscale(100%)

      - type: horizontal-stack #### 2nd row
        cards:
        - type: custom:button-card
          style: |
           ha-card {
              box-shadow: var(--card-box-shadow);
              margin: 0px 0px 0px 14px;
            }
          entity: input_boolean.enable_doorbell
          icon: '[[[ if (entity.state == "on") return "mdi:bell-ring-outline"; else return "mdi:bell-off-outline"; ]]]'
          tap_action: 
            action: toggle
          name: Deurbel 
          show_state: false
          confirmation:
            text: '[[[ return `Weet je zeker dat je de deurbel aan of uit wil zetten?` ]]]'
          styles:
            card:
              - width: 120px
              - height: 120px
            name:
              - font-size: 12px
          state:
            - value: 'off'
              styles:
                card:
                  - filter: opacity(50%)
                icon:
                  - filter: grayscale(100%)
        - type: custom:button-card
          entity: input_boolean.notify_door_alert
          tap_action: 
            action: toggle
            service: scene.turn_on
          name: Open deur alarm
          show_state: false
          confirmation:
            text: '[[[ return `Weet je zeker dat je de meldingen voor openstaande deuren wil wijzigen?` ]]]'
          styles:
            card:
              - width: 120px
              - height: 120px
            name:
              - font-size: 12px
          state:
            - value: 'off'
              styles:
                card:
                  - filter: opacity(50%)
                icon:
                  - filter: grayscale(100%)
        - type: custom:button-card
          entity: input_boolean.enable_cover
          icon: '[[[ if (entity.state == "on") return "mdi:garage"; else return "mdi:garage-alert"; ]]]'
          tap_action: 
            action: toggle
          name: Rolluik 
          show_state: false
          confirmation:
            text: '[[[ return `Weet je zeker dat je de rolluik automatisering aan of uit wil zetten?` ]]]'
          styles:
            card:
              - width: 120px
              - height: 120px
            name:
              - font-size: 12px
          state:
            - value: 'off'
              styles:
                card:
                  - filter: opacity(50%)
                icon:
                  - filter: grayscale(100%)

      - type: horizontal-stack #### 3rd row
        cards:
        - type: custom:button-card
          entity: input_boolean.notify_trash
          style: |
           ha-card {
              box-shadow: var(--card-box-shadow);
              margin: 0px 0px 0px 14px;
            }
          name: Afval push
          icon: '[[[ if (entity.state == "on") return "mdi:message-bulleted"; else return "mdi:message-bulleted-off"; ]]]'
          show_state: false
          confirmation:
            text: '[[[ return `Weet je zeker dat je de afval push-meldingen wil wijzigen? Bob gebruikt deze optie.` ]]]'
          styles:
            card:
              - width: 120px
              - height: 120px
            name:
              - font-size: 12px
          state:
            - value: 'off'
              styles:
                card:
                  - filter: opacity(50%)
                icon:
                  - filter: grayscale(100%)
        - type: custom:button-card
          entity: input_boolean.notify_trash_voice
          name: Afval Voice
          icon: '[[[ if (entity.state == "on") return "mdi:delete-outline"; else return "mdi:delete-off-outline"; ]]]'
          show_state: false
          confirmation:
            text: '[[[ return `Weet je zeker dat je de afvalmeldingen aan of uit wil zetten?` ]]]'
          styles:
            card:
              - width: 120px
              - height: 120px
            name:
              - font-size: 12px
          state:
            - value: 'off'
              styles:
                card:
                  - filter: opacity(50%)
                icon:
                  - filter: grayscale(100%)
        - type: custom:button-card
          entity: input_boolean.zigbee_permit_join
          name: Add Zigbee device
          tap_action: 
            action: toggle
          show_state: false
          confirmation:
            text: '[[[ return `Weet je zeker dat je een Zigbee apparaat wil toevoegen?` ]]]'
          styles:
            card:
              - width: 120px
              - height: 120px
            name:
              - font-size: 12px
          state:
            - value: 'off'
              styles:
                card:
                  - filter: opacity(50%)
                icon:
                  - filter: grayscale(100%)
      - type: horizontal-stack #### 4th row
        cards:
        - type: custom:button-card
          entity: input_boolean.notify_uv
          style: |
           ha-card {
              box-shadow: var(--card-box-shadow);
              margin: 0px 0px 0px 14px;
            }
          name: UV push
          icon: '[[[ if (entity.state == "on") return "mdi:message-bulleted"; else return "mdi:message-bulleted-off"; ]]]'
          show_state: false
          confirmation:
            text: '[[[ return `Weet je zeker dat je de UV push-meldingen wil wijzigen?` ]]]'
          styles:
            card:
              - width: 120px
              - height: 120px
            name:
              - font-size: 12px
          state:
            - value: 'off'
              styles:
                card:
                  - filter: opacity(50%)
                icon:
                  - filter: grayscale(100%)
        - type: custom:button-card
          entity: input_boolean.notify_uv_voice
          name: UV Voice
          icon: '[[[ if (entity.state == "on") return "mdi:weather-sunny"; else return "mdi:weather-sunny-off"; ]]]'
          show_state: false
          confirmation:
            text: '[[[ return `Weet je zeker dat je de UV-meldingen aan of uit wil zetten?` ]]]'
          styles:
            card:
              - width: 120px
              - height: 120px
            name:
              - font-size: 12px
          state:
            - value: 'off'
              styles:
                card:
                  - filter: opacity(50%)
                icon:
                  - filter: grayscale(100%)
        - type: custom:button-card
          entity: input_boolean.notify_zolder
          name: Meldingen leeslampje
          tap_action: 
            action: toggle
          show_state: false
          confirmation:
            text: '[[[ return `Weet je zeker dat je de zolder meldingen wil aanpassen?` ]]]'
          styles:
            card:
              - width: 120px
              - height: 120px
            name:
              - font-size: 12px
          state:
            - value: 'off'
              styles:
                card:
                  - filter: opacity(50%)
                icon:
                  - filter: grayscale(100%)
