####################
# Config           #
####################      
path: config
title: Config
icon: mdi:settings
cards:
  - type: vertical-stack
    cards:
    - type: horizontal-stack ### 1st row
      cards:
      - type: custom:button-card
        entity: input_boolean.enable_pir
        tap_action: 
          action: toggle
        name: Bewegingssensor
        icon: '[[[ if (entity.state == "on") return "mdi:motion-sensor"; else return "mdi:walk"; ]]]'
        show_state: false
        confirmation:
          text: '[[[ return `Weet je zeker dat je de status van de bewegingssensor wil wijzigen?` ]]]'
        styles:
          card:
            - width: 110px
            - height: 110px
          name:
            - font-size: 12px
        state:
          - value: 'off'
            styles:
              card:
                - filter: opacity(50%)
              icon:
                - filter: grayscale(100%)
      - type: custom:button-card
        entity: input_boolean.notify_door_alert
        tap_action: 
          action: toggle
          service: scene.turn_on
        name: Open deur alarm
        show_state: false
        confirmation:
          text: '[[[ return `Weet je zeker dat je de meldingen voor openstaande deuren wil wijzigen?` ]]]'
        styles:
          card:
            - width: 110px
            - height: 110px
          name:
            - font-size: 12px
        state:
          - value: 'off'
            styles:
              card:
                - filter: opacity(50%)
              icon:
                - filter: grayscale(100%)
      - type: custom:button-card
        entity: input_boolean.enable_doorbell
        icon: '[[[ if (entity.state == "on") return "mdi:bell-ring-outline"; else return "mdi:bell-off-outline"; ]]]'
        tap_action: 
          action: toggle
        name: Deurbel 
        show_state: false
        confirmation:
          text: '[[[ return `Weet je zeker dat je de deurbel aan of uit wil zetten?` ]]]'
        styles:
          card:
            - width: 110px
            - height: 110px
          name:
            - font-size: 12px
        state:
          - value: 'off'
            styles:
              card:
                - filter: opacity(50%)
              icon:
                - filter: grayscale(100%)
    - type: horizontal-stack #### 2nd row
      cards:
      - type: custom:button-card
        entity: input_boolean.notify_trash
        name: Afval push
        icon: '[[[ if (entity.state == "on") return "mdi:message-bulleted"; else return "mdi:message-bulleted-off"; ]]]'
        show_state: false
        confirmation:
          text: '[[[ return `Bob gebruikt deze optie. Weet je zeker dat je de afval meldingen wil wijzigen?` ]]]'
        styles:
          card:
            - width: 110px
            - height: 110px
          name:
            - font-size: 12px
        state:
          - value: 'off'
            styles:
              card:
                - filter: opacity(50%)
              icon:
                - filter: grayscale(100%)
      - type: custom:button-card
        entity: input_boolean.notify_trash_voice
        name: Afval Voice
        icon: '[[[ if (entity.state == "on") return "mdi:delete-outline"; else return "mdi:delete-off-outline"; ]]]'
        show_state: false
        confirmation:
          text: '[[[ return `Weet je zeker dat je de afvalmeldingen aan of uit wil zetten?` ]]]'
        styles:
          card:
            - width: 110px
            - height: 110px
          name:
            - font-size: 12px
        state:
          - value: 'off'
            styles:
              card:
                - filter: opacity(50%)
              icon:
                - filter: grayscale(100%)
      - type: custom:button-card
        entity: input_boolean.vacation_mode_away
        name: Vakantie weg
        show_state: false
        styles:
          card:
            - width: 110px
            - height: 110px
          name:
            - font-size: 12px
        state:
          - value: 'off'
            styles:
              card:
                - filter: opacity(50%)
              icon:
                - filter: grayscale(100%)

  - id: c78f07f54176407b123456923a45f12a  # Automatically created id
    type: entities
    title: Batterijen
    show_header_toggle: false
    entities:
      - entity: sensor.batterij_pir
        type: custom:battery-entity
      - entity: sensor.temp1_battery
        type: custom:battery-entity
        name: "Batterij zolder"
      - entity: sensor.temp2_battery
        type: custom:battery-entity
        name: "Batterij 1e verdieping"
      - entity: sensor.door_contact_1_battery
        type: custom:battery-entity
        name: "Batterij vriezer"
      - entity: sensor.door_contact_2_battery
        type: custom:battery-entity
        name: "Batterij voordeur"

  - id: c78f07f54176407b123456923a45f10a  # Automatically created id
    type: entities
    title: Statussen
    show_header_toggle: false
    entities:
      - binary_sensor.blauwe_lamp_status
      - binary_sensor.grijze_lamp_status
      - binary_sensor.staande_lamp_status
      - binary_sensor.bt_boven
      - binary_sensor.bt_beneden
      - binary_sensor.zigbee2mqtt_bridge

  - id: c78f07f54176407b123456923a45f11a  # Automatically created id
    type: entities
    title: Updates
    show_header_toggle: false
    entities:
      - sensor.ha_currently_installed
      - entity: sensor.hacs
        name: "HACS Updates"
