####################
# Config           #
####################      
path: config
title: Config
icon: mdi:settings
cards:
  - id: fd2fe96669a54eaeaf30a50d09abc5bb  # Automatically created id
    type: glance
    title: Meldingen
    show_header_toggle: true
    entities:
      - entity: input_boolean.notify_trash
        tap_action: 
          action: toggle
        name: Afval push
      - entity: input_boolean.notify_trash_voice
        tap_action: 
          action: toggle
        name: Afval Voice
      - entity: input_boolean.vacation_mode_home
        tap_action: 
          action: toggle
        name: Vakantie thuis
      - entity: input_boolean.vacation_mode_away
        tap_action: 
          action: toggle
        name: Vakantie weg

  - id: c78f07f54176407b123456923a45f10a  # Automatically created id
    type: entities
    title: Statussen
    show_header_toggle: false
    entities:
      - binary_sensor.blauwe_lamp_status
      - binary_sensor.grijze_lamp_status
      - binary_sensor.staande_lamp_status
      - binary_sensor.bt_boven
      - binary_sensor.bt_beneden
      - binary_sensor.zigbee2mqtt_bridge
      - entity: sensor.batterij_pir
        type: custom:battery-entity
      - entity: sensor.temp1_battery
        type: custom:battery-entity
        name: "Batterij zolder"
      - entity: sensor.temp2_battery
        type: custom:battery-entity
      - sensor.ha_currently_installed

  - id: c78f07f54176407b928ef6923a45f10a  # Automatically created id
    type: entities
    title: PIR
    show_header_toggle: false
    entities:
      - binary_sensor.pir_sensor_motion
      - sensor.pir_sensor_luminance
      - input_boolean.eetkamer_on_movement
      - input_boolean.woonkamer_on_movement

  - id: c78f01234176407b123456923a45f10a  # Automatically created id
    type: entities
    title: Zigbee2mqtt
    show_header_toggle: false
    entities:
      - input_boolean.zigbee_permit_join
      - timer.zigbee_permit_join
      - switch.zigbee2mqtt_main_join
      - input_select.zigbee2mqtt_log_level

