swipe_nav:
  animate: swipe

title: Home sweet home
views:
  - !include lovelace/1-start.yaml
  - !include lovelace/2-temp.yaml
  - !include lovelace/3-locations.yaml
  - !include lovelace/4-settings.yaml
  - !include lovelace/5-status.yaml
  - !include lovelace/6-development.yaml
  - !include lovelace/7-dsmr_development.yaml
