resources:
  - url: /community_plugin/mini-media-player/mini-media-player.js
    type: module
  - url: /community_plugin/lovelace-slider-entity-row/slider-entity-row.js
    type: js
  - url: /community_plugin/monster-card/monster-card.js
    type: js
  - url: /community_plugin/weather-card/weather-card.js
    type: module
  - url: https://unpkg.com/moment@2.24.0/moment.js
    type: js
  - url: /community_plugin/lovelace-postnl-card/postnl-card.js
    type: module
  - url: /community_plugin/mini-graph-card/mini-graph-card.js
    type: module
  - url: /community_plugin/lovelace-battery-entity/battery-entity.js
    type: module   

title: Home sweet home
views:
  - !include lovelace/frontpage.yaml
  - !include lovelace/location.yaml
  - !include lovelace/media.yaml
  - !include lovelace/config.yaml
  - !include lovelace/zolder.yaml
  - !include lovelace/power.yaml
  - !include lovelace/overviews.yaml