swipe_nav:
  animate: swipe

title: Home sweet home
views:
  - !include dashboards/1-start.yaml
  - !include dashboards/2-temp.yaml
  - !include dashboards/2.1-airco.yaml
  - !include dashboards/3-vacuum.yaml
  - !include dashboards/4-locations.yaml
  - !include dashboards/5-plants.yaml
  - !include dashboards/6-camera.yaml
  - !include dashboards/7-energy.yaml
  - !include dashboards/8-car.yaml
  - !include dashboards/99-settings.yaml
