swipe_nav:
  animate: swipe

apexcharts_card_templates: !include dashboards/apexcharts_card_templates.yaml

title: Home sweet home
views:
  - !include dashboards/1-start.yaml
  - !include dashboards/3-temp.yaml
  - !include dashboards/10-energy.yaml
  - !include dashboards/4-locations.yaml
  - !include dashboards/9-camera.yaml
  - !include dashboards/2-vacuum.yaml
  - !include dashboards/5-settings.yaml
  - !include dashboards/6-status.yaml
  - !include dashboards/11-f1.yaml
  - !include dashboards/7-development.yaml
  - !include dashboards/8-dsmr_development.yaml
