##########################
## Treininformatie
##########################
- id: Notification_trein_naar_Breda
  alias: "Trein: Notificatie vertrektijd Oss naar Breda"
  trigger:
  - platform: zone
    entity_id: device_tracker.bob_s9
    event: enter
    zone: zone.stationoss
  condition:
  - condition: state
    entity_id: input_boolean.notify_train
    state: 'on'
  - condition: time
    after: 06:15:00
    before: 08:30:00
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
#  - data:
#      message: Vertrektijd {{ states.sensor.ossbreda.attributes.departure_time_actual
#        }} vanaf spoor {{ states.sensor.ossbreda.attributes.departure_platform
#        }}, aankomst om {{ states.sensor.ossbreda.attributes.arrival_time_actual
#        }}. Volgende trein vertrekt om {{ states.sensor.ossbreda.attributes.next
#        }}.
#      title: 'Trein naar Breda: {{ states.sensor.ossbreda.attributes.status
#        }}.'
#    service: notify.pushbullet
  - service: notify.google
    data:
      message: Vertrektijd {{ states.sensor.ossbreda.attributes.departure_time_actual
        }} vanaf spoor {{ states.sensor.ossbreda.attributes.departure_platform
        }}, aankomst om {{ states.sensor.ossbreda.attributes.arrival_time_actual
        }}. Volgende trein vertrekt om {{ states.sensor.ossbreda.attributes.next
        }}.
      title: 'Trein naar Breda: {{ states.sensor.ossbreda.attributes.status
        }}.'
    data:
      data:
        tag: 'notification-trein-naar-breda'

- id: Notification_vertrek_naar_Oss
  alias: "Trein: Notificatie vertrektijd Breda naar Oss"
  trigger:
  - entity_id: sensor.bredaoss
    platform: state
  condition:
  - condition: state
    entity_id: input_boolean.notify_train
    state: 'on'
  - condition: and
    conditions:
    - after: '15:00:00'
      before: '16:30:00'
      condition: time
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
    - condition: state
      entity_id: device_tracker.bob_s9
      state: work
  action:
#  - data:
#      message: Vertrektijd {{ states.sensor.bredaoss.attributes.departure_time_actual
#        }} vanaf spoor {{ states.sensor.bredaoss.attributes.departure_platform
#        }}, aankomst om {{ states.sensor.bredaoss.attributes.arrival_time_actual
#        }} op spoor {{ states.sensor.bredaoss.attributes.arrival_platform }}.
#        Volgende trein vertrekt om {{ states.sensor.bredaoss.attributes.next
#        }}.
#      title: 'Trein naar Den Bosch: {{ states.sensor.bredaoss.attributes.status
#        }}.'
#    service: notify.pushbullet
  - service: notify.google
    data:
      message: Vertrektijd {{ states.sensor.bredaoss.attributes.departure_time_actual
        }} vanaf spoor {{ states.sensor.bredaoss.attributes.departure_platform
        }}, aankomst om {{ states.sensor.bredaoss.attributes.arrival_time_actual
        }} op spoor {{ states.sensor.bredaoss.attributes.arrival_platform }}.
        Volgende trein vertrekt om {{ states.sensor.bredaoss.attributes.next
        }}.
      title: 'Trein naar Oss: {{ states.sensor.bredaoss.attributes.status
        }}.'
    data:
      data:
        tag: 'notification-trein-naar-oss'


#########################
# Device tracker notifications
#########################
- id: Set_notification_Bob_Home_owntrak_mqtt
  alias: "Location: notificatie dat Bob thuis is"
  initial_state: false
  trigger:
    - entity_id: device_tracker.sm_a505fn
      from: not_home
      platform: state
      to: home
  action:
    - service: notify.mobile_app_sm_a505fn
      data:
        message: Bob was om {{now().strftime("%H:%M:%S %d-%m-%Y")}} thuis!
        title: Bob is thuis!

- id: Set_notification_Bob_arrive_work_owntrak_mqtt
  alias: "Location: Notificatie dat Bob op het werk arriveert"
  initial_state: false
  trigger:
    - platform: zone
      entity_id: device_tracker.sm_a505fn
      event: enter
      zone: zone.Work
  action:
    - service: notify.mobile_app_sm_a505fn
      data:
        message: Bob was om {{now().strftime("%H:%M:%S %d-%m-%Y")}} op het werk.
        title: Bob is op het werk!

- id: Set_notification_Bob_leave_work_owntrak_mqtt
  alias: "Location: Notificatie dat Bob van het werk vertrekt"
  initial_state: false
  trigger:
    - platform: zone
      entity_id: device_tracker.sm_a505fn
      event: leave
      zone: zone.Work
  action:
    - service: notify.mobile_app_sm_a505fn
      data:
        message: Bob verliet om {{now().strftime("%H:%M:%S %d-%m-%Y")}} het werk.
        title: Bob is op weg naar huis!
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.bob_werk_verlaten

- id: TTS_notification_Bob_Home_owntrak_mqtt
  alias: "Location: TTS Notificatie dat Bob thuis is"
  initial_state: false
  trigger:
    - entity_id: device_tracker.sm_a505fn
      from: not_home
      platform: state
      to: home
  condition:
    - condition: time
      after: "15:00:00"
      before: "19:00:00"
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: state
      entity_id: input_boolean.bob_werk_verlaten
      state: "on"
  action:
    # - service: media_player.volume_set
    #   data:
    #     entity_id: media_player.woonkamer
    #     volume_level: 0.6
    - service: tts.microsoft_say
      entity_id: media_player.woonkamer
      data:
        message: Papa is thuis
        language: nl
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.bob_werk_verlaten
