####################
# Config           #
####################
path: config
title: Config
icon: mdi:settings
cards:
  - type: vertical-stack
    cards:
      - type: horizontal-stack ### 1st row
        cards:
          - type: custom:button-card
            entity: input_boolean.enable_pir_woonkamer
            tap_action:
              action: toggle
            name: Woonkamer
            icon: '[[[ if (entity.state == "on") return "mdi:motion-sensor"; else return "mdi:walk"; ]]]'
            show_state: false
            confirmation:
              text: "[[[ return `Weet je zeker dat je de status van de bewegingssensor in de woonkamer wil wijzigen?` ]]]"
            styles:
              card:
                - width: 110px
                - height: 110px
              name:
                - font-size: 12px
            state:
              - value: "off"
                styles:
                  card:
                    - filter: opacity(50%)
                  icon:
                    - filter: grayscale(100%)
          - type: custom:button-card
            entity: input_boolean.enable_pir_gang
            tap_action:
              action: toggle
            name: Gang
            icon: '[[[ if (entity.state == "on") return "mdi:motion-sensor"; else return "mdi:walk"; ]]]'
            show_state: false
            confirmation:
              text: "[[[ return `Weet je zeker dat je de status van de bewegingssensor in de gang wil wijzigen?` ]]]"
            styles:
              card:
                - width: 110px
                - height: 110px
              name:
                - font-size: 12px
            state:
              - value: "off"
                styles:
                  card:
                    - filter: opacity(50%)
                  icon:
                    - filter: grayscale(100%)
          - type: custom:button-card
            entity: input_boolean.notify_door_alert
            tap_action:
              action: toggle
              service: scene.turn_on
            name: Open deur alarm
            show_state: false
            confirmation:
              text: "[[[ return `Weet je zeker dat je de meldingen voor openstaande deuren wil wijzigen?` ]]]"
            styles:
              card:
                - width: 110px
                - height: 110px
              name:
                - font-size: 12px
            state:
              - value: "off"
                styles:
                  card:
                    - filter: opacity(50%)
                  icon:
                    - filter: grayscale(100%)
      - type: horizontal-stack #### 2nd row
        cards:
          - type: custom:button-card
            entity: input_boolean.enable_deurbel
            icon: '[[[ if (entity.state == "on") return "mdi:bell-ring-outline"; else return "mdi:bell-off-outline"; ]]]'
            tap_action:
              action: toggle
            name: Deurbel
            show_state: false
            confirmation:
              text: "[[[ return `Weet je zeker dat je de deurbel aan of uit wil zetten?` ]]]"
            styles:
              card:
                - width: 110px
                - height: 110px
              name:
                - font-size: 12px
            state:
              - value: "off"
                styles:
                  card:
                    - filter: opacity(50%)
                  icon:
                    - filter: grayscale(100%)
          - type: custom:button-card
            entity: input_boolean.notify_trash
            name: Afval push
            icon: '[[[ if (entity.state == "on") return "mdi:message-bulleted"; else return "mdi:message-bulleted-off"; ]]]'
            show_state: false
            confirmation:
              text: "[[[ return `Bob gebruikt deze optie. Weet je zeker dat je de afval meldingen wil wijzigen?` ]]]"
            styles:
              card:
                - width: 110px
                - height: 110px
              name:
                - font-size: 12px
            state:
              - value: "off"
                styles:
                  card:
                    - filter: opacity(50%)
                  icon:
                    - filter: grayscale(100%)
          - type: custom:button-card
            entity: input_boolean.notify_trash_voice
            name: Afval Voice
            icon: '[[[ if (entity.state == "on") return "mdi:delete-outline"; else return "mdi:delete-off-outline"; ]]]'
            show_state: false
            confirmation:
              text: "[[[ return `Weet je zeker dat je de afvalmeldingen aan of uit wil zetten?` ]]]"
            styles:
              card:
                - width: 110px
                - height: 110px
              name:
                - font-size: 12px
            state:
              - value: "off"
                styles:
                  card:
                    - filter: opacity(50%)
                  icon:
                    - filter: grayscale(100%)
  #      - type: custom:button-card
  #        entity: input_boolean.vacation_mode_away
  #        name: Vakantie weg
  #        show_state: false
  #        styles:
  #          card:
  #            - width: 110px
  #            - height: 110px
  #          name:
  #            - font-size: 12px
  #        state:
  #          - value: 'off'
  #            styles:
  #              card:
  #                - filter: opacity(50%)
  #              icon:
  #                - filter: grayscale(100%)

  - id: c78f07f54176407b123456923a45f12a # Automatically created id
    type: custom:battery-state-card
    title: Batterijen
    show_header_toggle: false
    entities:
      - entity: sensor.pir_woonkamer_battery_level
      - entity: sensor.pir_gang_battery_level
      - entity: sensor.temp1_battery
        name: "Batterij temp zolder"
      - entity: sensor.temp2_battery
        name: "Batterij temp 1e verdieping"
      - entity: sensor.door_contact_1_battery
        name: "Batterij deur vriezer"
      - entity: sensor.door_contact_2_battery
        name: "Batterij voordeur"

  - id: c78f07f54176407b123456923a45f10a # Automatically created id
    type: entities
    title: Statussen
    show_header_toggle: false
    state_color: true
    entities:
      - binary_sensor.blauwe_lamp_status
      - binary_sensor.grijze_lamp_status
      - binary_sensor.staande_lamp_status
      - binary_sensor.bt_boven
      - binary_sensor.bt_beneden
      - binary_sensor.zigbee2mqtt_bridge

  - id: c78f07f54176407b123456923a45f11a # Automatically created id
    type: entities
    title: Updates
    show_header_toggle: false
    entities:
      - entity: sensor.current_version
        name: "Docker image installed"
      - entity: sensor.latest_version
        name: "Latest Docker image"
      - entity: sensor.hacs
        name: "HACS Updates"
        state_color: true
