##################################
## Push values to Air Quality APIs
##################################
# Sensor uses a NodeMCUv2 and SDS011+BME280 sensors.
# All BME280 sensors update at the same time, so we only
# need to monitor one sensor to trigger the automation.
# Temperature is the one that changes most often.
- alias: 'Update Temp/Pres/Hum'
  initial_state: true
  mode: queued
  trigger: # Trigger on every update of the temperature
    platform: state
    entity_id: sensor.bme280_temperature 
  action:
    ## Send to Luftdaten / Sensor.Community API
    ## Split over two calls as the headers differ
    - service: rest_command.send_luftdaten_tph
    - service: rest_command.send_luftdaten_pm
    ## Send updates to Madavi.de too for statistics.
    - service: rest_command.send_madavi
    ## Send data to OpenSenseMap. 
    - service: rest_command.post_opensensebox