##########################
## Clear alerts
##########################
# When alerts are cleared, mobile notifications aren't
# cleared automatically too. But we can automate that!

- alias: "Notifications: Clear alerts"
  id: 6cd827a2-bb9b-4376-981b-8dabd5a23084
  trigger:
    - platform: state
      entity_id: alert.freezer_door
      from: "on"
      to:
        - "idle"
        - "off"
      id: freezer_door_alert
    - platform: state
      entity_id: alert.front_door
      from: "on"
      to:
        - "idle"
        - "off"
      id: front_door_alert
    - platform: state
      entity_id: alert.weerhuisje
      from: "on"
      to:
        - "idle"
        - "off"
      id: weerhuisje
  variables:
    tag: "{{ trigger.id }}"
  action:
    - service: notify.mobile_devices_adults
      data:
        message: clear_notification
        data:
          tag: "{{ tag }}"

##########################
## Mute alerts
##########################
- alias: "Notifications: handle alert mute"
  id: mute_door_alerts
  initial_state: "on"
  trigger:
    - platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: "mute_alert_freezer"
      id: freezer_door
    - platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: "mute_alert_front_door"
      id: front_door
    - platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: "mute_alert_weerhuisje"
      id: weerhuisje
  variables:
    alert: "alert.{{ trigger.id }}"
  action:
    - service: alert.turn_off
      target:
        entity_id: "{{ alert }}"
