##########################
## Deurbel
##########################
- alias: "Deurbel: Play doorbell"
  id: deurbel_notify
  mode: single
  max_exceeded: silent
  variables:
    dingdong: >
      {% if is_state("input_select.deurbel", "Star Wars") %} {{ states('input_text.deurbel_url_star_wars') }}
      {% elif is_state("input_select.deurbel", "Sinterklaas") %} {{ states('input_text.deurbel_url_sinterklaas') }}
      {% elif is_state("input_select.deurbel", "Jingle Bells") %} {{ states('input_text.deurbel_url_jingle_bells') }}
      {% elif is_state("input_select.deurbel", "Savage Love") %} {{ states('input_text.deurbel_url_savage_love') }}
      {% endif %}
  trigger:
    - platform: state
      entity_id: binary_sensor.deurbel
      from: "off"
      to: "on"
  condition:
    - condition: state
      entity_id: input_boolean.enable_deurbel
      state: "on"
  action:
    - choose:
        # During daytime we want the doorbell to play
        # in sync through the whole house
        - alias: "Is it between 8 and 19hrs?"
          conditions:
            - condition: time
              after: "08:00:00"
              before: "19:00:00"
          sequence:
            # Cut up in two different actions to speed up playing downstairs
            - alias: "Play doorbell sound downstairs"
              service: media_player.play_media
              data:
                entity_id:
                  - media_player.woonkamer
                media_content_type: music
                media_content_id: "{{ dingdong }}"
            - alias: "Play doorbell sound upstairs"
              service: media_player.play_media
              data:
                entity_id:
                  - media_player.boven
                media_content_type: music
                media_content_id: "{{ dingdong }}"
            - alias: "Kick off some notifications"
              service: script.turn_on
              entity_id:
                - script.send_doorbell_notification
                - script.show_doorbell_alert
            - alias: "Wait a bit for the music to finish..."
              delay: "00:00:15"
            - alias: "Turn off everything we used"
              service: media_player.turn_off
              entity_id:
                - media_player.woonkamer
                - media_player.boven
        # Early morning or late at night, we only
        # want the doorbell to play in the living room
        - alias: "Is it between 7 and 8, or 19 and 23hrs?"
          conditions:
            - condition: or
              conditions:
                - condition: time
                  after: "07:00:00"
                  before: "08:00:00"
                - condition: time
                  after: "19:00:00"
                  before: "23:00:00"
          sequence:
            - alias: "Play doorbell sound downstairs only"
              service: media_player.play_media
              data:
                entity_id: media_player.woonkamer
                media_content_type: music
                media_content_id: "{{ dingdong }}"
            - alias: "Kick off some notifications"
              service: script.turn_on
              entity_id:
                - script.send_doorbell_notification
                - script.show_doorbell_alert
            - alias: "Wait a bit for the music to finish..."
              delay: "00:00:15"
            - alias: "Turn off everything we used"
              service: media_player.turn_off
              entity_id:
                - media_player.woonkamer
