##########################
## Doorbell
##########################

### Play doorbell alerts
- alias: "Doorbell: Notify"
  id: doorbell_notify
  initial_state: on
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.doorbell
      from: "off"
      to: "on"
  condition:
    - condition: state
      entity_id: input_boolean.enable_doorbell
      state: "on"
  action:
    - service: script.turn_on
      entity_id:
        - script.ring_doorbell_downstairs
        - script.ring_doorbell_upstairs
        - script.show_doorbell_alert
