##########################
## Deurbel
##########################
- alias: "Deurbel: play doorbell"
  id: deurbel_notify
  initial_state: on
  mode: single
  max_exceeded: silent
  trigger:
    - platform: state
      entity_id: binary_sensor.deurbel
      from: "off"
      to: "on"
  condition:
    - condition: state
      entity_id: input_boolean.enable_deurbel
      state: "on"
  action:
    - choose:
        # During daytime we want the doorbell to play
        # in sync through the while house
        - conditions:
            - condition: time
              after: "08:00:00"
              before: "19:00:00"
          sequence:
            - service: media_player.play_media
              data:
                entity_id: media_player.woonkamer
                media_content_type: music
                media_content_id: >
                  {% if is_state("input_select.deurbel", "Star Wars") %} {{ states('input_text.deurbel_url_star_wars') }}
                  {% elif is_state("input_select.deurbel", "Sinterklaas") %} {{ states('input_text.deurbel_url_sinterklaas') }}
                  {% elif is_state("input_select.deurbel", "Jingle Bells") %} {{ states('input_text.deurbel_url_jingle_bells') }}
                  {% endif %}
            - service: media_player.volume_set
              data:
                entity_id: media_player.woonkamer
                volume_level: 0.8
            - service: media_player.play_media
              data:
                entity_id: media_player.boven
                media_content_type: music
                media_content_id: >
                  {% if is_state("input_select.deurbel", "Star Wars") %} {{ states('input_text.deurbel_url_star_wars') }}
                  {% elif is_state("input_select.deurbel", "Sinterklaas") %} {{ states('input_text.deurbel_url_sinterklaas') }}
                  {% elif is_state("input_select.deurbel", "Jingle Bells") %} {{ states('input_text.deurbel_url_jingle_bells') }}
                  {% endif %}
            - service: script.turn_on
              entity_id:
                - script.show_deurbel_alert
            - delay: "00:00:04"
            # Ensure Home Hub screen is back to photo mode
            - wait_template: "{{ is_state('media_player.woonkamer', 'idle') }}"
            - service: media_player.volume_set
              data:
                entity_id: media_player.woonkamer
                volume_level: 0.5
            - service: media_player.turn_off
              entity_id:
                - media_player.woonkamer
                - media_player.boven
        # Early morning or late at night, we only
        # want the doorbell to play in the living room
        - conditions:
            - condition: or
              conditions:
                - condition: time
                  after: "07:00:00"
                  before: "08:00:00"
                - condition: time
                  after: "19:00:00"
                  before: "22:00:00"
          sequence:
            - service: media_player.play_media
              data:
                entity_id: media_player.woonkamer
                media_content_type: music
                media_content_id: >
                  {% if is_state("input_select.deurbel", "Star Wars") %} {{ states('input_text.deurbel_url_star_wars') }}
                  {% elif is_state("input_select.deurbel", "Sinterklaas") %} {{ states('input_text.deurbel_url_sinterklaas') }}
                  {% elif is_state("input_select.deurbel", "Jingle Bells") %} {{ states('input_text.deurbel_url_jingle_bells') }}
                  {% endif %}
            - service: media_player.volume_set
              data:
                entity_id: media_player.woonkamer
                volume_level: 0.8
            - service: script.turn_on
              entity_id:
                - script.show_deurbel_alert
            - delay: "00:00:04"
            # Ensure Home Hub screen is back to photo mode
            - wait_template: "{{ is_state('media_player.woonkamer', 'idle') }}"
            - service: media_player.volume_set
              data:
                entity_id: media_player.woonkamer
                volume_level: 0.5
            - service: media_player.turn_off
              entity_id:
                - media_player.woonkamer
