- alias: "Energy: Notification for negative electricity price tomorrow"
  trigger:
    platform: state
    entity_id: binary_sensor.nordpool_negative_electricity_price_tomorrow
    to: "on"
    from: "off"
  action:
    - service: notify.mobile_app_sm_a526b
      data:
        title: "Negative electricity price tomorrow"
        message: "There are one or more hour with negative electricity prices tomorrow!"
        data:
          channel: "Energy"
          importance: high
          notification_icon: "mdi:home-lightning-bolt"
          actions:
            - action: "URI"
              title: "Check overzicht"
              uri: "/lovelace/energy"
