##########################
## Trash
##########################
- alias: "Afval: Melding vandaag"
  id: melding_afval_vandaag
  initial_state: true
  trigger:
    platform: time
    at: input_datetime.time_trash_warning_today
  condition:
    - condition: state
      entity_id: input_boolean.notify_trash
      state: "on"
    - condition: not
      conditions:
        - condition: state
          entity_id: sensor.afvalinfo_today
          state: "none"
        - condition: state
          entity_id: sensor.afvalinfo_today
          state: "unavailable"
  action:
    - service: notify.mobile_app_sm_a505fn
      data:
        title: "Afvalinzameling"
        message: "Vandaag wordt het {{ states('sensor.afvalinfo_today') }} opgehaald."
        data:
          tag: "notification-trash"
    - condition: state
      entity_id: input_boolean.notify_trash_voice
      state: "on"
    - service: tts.microsoft_say
      entity_id: media_player.woonkamer
      data:
        message: "Vandaag wordt het {{ states('sensor.afvalinfo_today') }} opgehaald."
    - delay: "00:00:05"
    - wait_template: "{{ is_state('media_player.woonkamer', 'idle') }}" # Ensure TTS is done
    - choose:
        - conditions:
            - condition: state
              entity_id: sensor.afvalinfo_today
              state: "pbd"
          sequence:
            - service: media_player.play_media
              data:
                entity_id: media_player.woonkamer
                media_content_id: !secret image_url_plastic
                media_content_type: "image/png"
        - conditions:
            - condition: state
              entity_id: sensor.afvalinfo_today
              state: "restafval"
          sequence:
            - service: media_player.play_media
              data:
                entity_id: media_player.woonkamer
                media_content_id: !secret image_url_restafval
                media_content_type: "image/png"
        - conditions:
            - condition: state
              entity_id: sensor.afvalinfo_today
              state: "gft"
          sequence:
            - service: media_player.play_media
              data:
                entity_id: media_player.woonkamer
                media_content_id: !secret image_url_gft
                media_content_type: "image/png"
        - conditions:
            - condition: state
              entity_id: sensor.afvalinfo_today
              state: "papier"
          sequence:
            - service: media_player.play_media
              data:
                entity_id: media_player.woonkamer
                media_content_id: !secret image_url_oudpapier
                media_content_type: "image/png"
        - conditions:
            - condition: state
              entity_id: sensor.afvalinfo_today
              state: "papier, pbd"
          sequence:
            - service: media_player.play_media
              data:
                entity_id: media_player.woonkamer
                media_content_id: !secret image_url_plasticpapier
                media_content_type: "image/png"
    - delay: "00:15:00"
    - service: media_player.turn_off
      entity_id:
        - media_player.woonkamer

- alias: "Afval: Melding morgen"
  id: melding_afval_morgen
  initial_state: true
  trigger:
    platform: time
    at: input_datetime.time_trash_warning_tomorrow
  condition:
    - condition: state
      entity_id: input_boolean.notify_trash
      state: "on"
    - condition: not
      conditions:
        - condition: state
          entity_id: sensor.afvalinfo_tomorrow
          state: "none"
        - condition: state
          entity_id: sensor.afvalinfo_tomorrow
          state: "unavailable"
  action:
    - service: notify.mobile_app_sm_a505fn
      data:
        title: "Afvalinzameling"
        message: "Morgen wordt het {{ states('sensor.afvalinfo_tomorrow') }} opgehaald."
        data:
          tag: "notification-trash"
    - condition: state
      entity_id: input_boolean.notify_trash_voice
      state: "on"
    - service: tts.microsoft_say
      entity_id: media_player.woonkamer
      data:
        message: "Morgen wordt het {{ states('sensor.afvalinfo_tomorrow') }} opgehaald."
    - delay: "00:00:05"
    - wait_template: "{{ is_state('media_player.woonkamer', 'idle') }}" # Ensure TTS is done
    - choose:
        - conditions:
            - condition: state
              entity_id: sensor.afvalinfo_tomorrow
              state: "pbd"
          sequence:
            - service: media_player.play_media
              data:
                entity_id: media_player.woonkamer
                media_content_id: !secret image_url_plastic
                media_content_type: "image/png"
        - conditions:
            - condition: state
              entity_id: sensor.afvalinfo_tomorrow
              state: "restafval"
          sequence:
            - service: media_player.play_media
              data:
                entity_id: media_player.woonkamer
                media_content_id: !secret image_url_restafval
                media_content_type: "image/png"
        - conditions:
            - condition: state
              entity_id: sensor.afvalinfo_tomorrow
              state: "gft"
          sequence:
            - service: media_player.play_media
              data:
                entity_id: media_player.woonkamer
                media_content_id: !secret image_url_gft
                media_content_type: "image/png"
        - conditions:
            - condition: state
              entity_id: sensor.afvalinfo_tomorrow
              state: "papier"
          sequence:
            - service: media_player.play_media
              data:
                entity_id: media_player.woonkamer
                media_content_id: !secret image_url_oudpapier
                media_content_type: "image/png"
        - conditions:
            - condition: state
              entity_id: sensor.afvalinfo_tomorrow
              state: "papier, pbd"
          sequence:
            - service: media_player.play_media
              data:
                entity_id: media_player.woonkamer
                media_content_id: !secret image_url_plasticpapier
                media_content_type: "image/png"
    - delay: "00:15:00"
    - service: media_player.turn_off
      entity_id:
        - media_player.woonkamer
