##########################
## Trash notifications
##########################
- alias: "Afval: Meldingen"
  id: melding_afval
  initial_state: true
  trigger:
    - platform: time
      at: input_datetime.time_trash_warning_today
      id: Vandaag_today
    - platform: time
      at: input_datetime.time_trash_warning_tomorrow
      id: Morgen_tomorrow
  variables:
    sensor: "sensor.afvalinfo_{{ trigger.id.split('_')[1] }}"
    trash_descr:
      pbd: "plastic"
      gft: "GFT"
      restafval: "restafval"
      papier: "oud papier"
      pbd papier: "plastic en oud papier"
      papier pbd: "plastic en oud papier"
    afval: >
      {{ trash_descr.get(states(sensor), "onbekend") }}
  condition:
    - alias: "Do we want notifications?"
      condition: state
      entity_id: input_boolean.notify_trash
      state: "on"
    - alias: "Do we need to send a notification"
      condition: template
      value_template: "{{ states(sensor) not in ['unknown','unavailable','none'] }}"
  action:
    - alias: "Sending push notification"
      service: notify.mobile_app_sm_a526b
      data:
        title: "Afvalinzameling"
        message: "{{ trigger.id.split('_')[0] }} wordt het {{ afval }} opgehaald."
        data:
          tag: "notification-trash"
          icon_url: "https://raw.githubusercontent.com/home-assistant/assets/master/logo/logo-pretty.png"
          notification_icon: mdi:delete
    - alias: "Check if TTS should be played"
      condition: state
      entity_id: input_boolean.notify_trash_voice
      state: "on"
    - alias: "Play TTS"
      service: tts.microsoft_say
      entity_id: media_player.woonkamer
      data:
        message: "{{ trigger.id.split('_')[0] }} wordt het {{ afval }} opgehaald."
    - delay: "00:00:15"
    - alias: "Streaming image to Nest Hub"
      service: media_player.play_media
      data:
        entity_id: media_player.woonkamer
        media_content_id: "{{ states('input_text.trash_url_' ~ states(sensor).replace(' ', '')) }}"
        media_content_type: "image/png"
    - delay: "00:15:00"
    - service: media_player.turn_off
      entity_id: media_player.woonkamer
