##########################
## Update Waze sensors
##########################
- id: waze_update_to_home
  alias: "Waze: update to home"
  initial_state: on
  trigger:
    - platform: time_pattern
      minutes: "/5"
      seconds: 00
    - platform: homeassistant
      event: start
  condition:
    condition: state
    entity_id: person.bob
    state: not_home
  action:
    - service: homeassistant.update_entity
      entity_id: sensor.reistijd_bob_naar_huis

##########################
## Coming home notifications
##########################
- id: notification_hmmbob_left_work
  alias: "Location: Notificatie dat Bob van het werk vertrekt"
  initial_state: on
  trigger:
    - platform: zone
      entity_id: device_tracker.sm_a526b
      event: leave
      zone: zone.work
  condition:
    - condition: time
      after: "15:00:00"
      before: "19:00:00"
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    - service: homeassistant.update_entity
      entity_id: sensor.reistijd_bob_naar_huis
    - delay:
        seconds: 10
    - service: notify.mobile_app_moto_g_8_plus
      data:
        title: ♥ Bob is op weg naar huis!
        message: >
          Hij is rond {{now().strftime("%H:%M")}} vertrokken en Waze 
          denkt dat hij over {{states('sensor.reistijd_bob_naar_huis')}} min thuis is.
        data:
          actions:
            - action: "URI"
              title: "Check huidige locatie"
              uri: "/lovelace/locations"
    - service: notify.mobile_app_sm_a526b
      data:
        title: Goede thuisreis
        message: >
          Ik heb thuis laten weten dat je volgens Waze over {{states('sensor.reistijd_bob_naar_huis')}} min thuis bent.

- id: notification_m_left_school
  alias: "Location: Notificatie dat M van school vertrekt"
  initial_state: on
  trigger:
    - platform: zone
      entity_id: device_tracker.schaduwspeler
      event: leave
      zone: zone.school
  condition:
    - condition: time
      after: "12:00:00"
      before: "18:00:00"
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    - service: notify.mobile_devices_adults
      data:
        title: ♥ {{states('input_text.naam_puber')}} is op weg naar huis!
        message: >
          {{states('input_text.naam_puber')}} is rond {{now().strftime("%H:%M")}} van school vertrokken.
        data:
          actions:
            - action: "URI"
              title: "Check huidige locatie"
              uri: "/map"

##########################
## Battery level notifications
##########################
- id: notification_m_battery_low
  alias: "Updates: Notificatie dat batterij van M opgeladen moet worden"
  initial_state: on
  trigger:
    - platform: time
      at: "20:00:00"
  condition:
    - condition: numeric_state
      entity_id: sensor.schaduwspeler_batterijniveau
      below: 40
    - condition: state
      entity_id: binary_sensor.schaduwspeler_is_aan_het_opladen
      state: "off"
  action:
    - service: notify.mobile_app_schaduwspeler
      data:
        title: 🔋 Batterijwaarschuwing
        message: >
          Je moet je telefoon even opladen....

- id: notification_m_battery_low_parents
  alias: "Updates: Notificatie dat batterij van M bijna leeg is"
  initial_state: on
  trigger:
    - platform: numeric_state
      entity_id: sensor.schaduwspeler_batterijniveau
      below: 10
  condition:
    - condition: state
      entity_id: device_tracker.schaduwspeler
      state: not_home
  action:
    - service: notify.mobile_devices_adults
      data:
        title: 🔋 Batterijwaarschuwing
        message: >
          De telefoon van {{states('input_text.naam_puber')}} is bijna leeg. Updates van zijn locatie zullen snel stoppen.

##########################
## System update notifications
##########################
- alias: "System: Upgrade Available Notification"
  id: system_update_available_notification
  description: Send notification on Home Assistant update available
  trigger:
    - platform: state
      entity_id: sensor.latest_version
  condition:
    - condition: template
      value_template: >
        {{ states('sensor.latest_version') != states('sensor.current_version') }}
  action:
    - service: notify.mobile_app_sm_a526b
      data:
        title: Upgrade time!
        message: >
          There is an upgrade for Home Assistant container pending!
          Version {{ states('sensor.latest_version') }} just got released!
        data:
          tag: System
          channel: System
          actions:
            - action: "URI"
              title: "Open Changelog"
              uri: "https://github.com/home-assistant/core/releases/tag/{{states('sensor.latest_version')}}"
    - service: persistent_notification.create
      data:
        notification_id: update_pending
        title: Upgrade time!
        message: >
          There is an upgrade for Home Assistant container pending!
          Version {{ states('sensor.latest_version') }} just got released!
          [Changelog](https://github.com/home-assistant/core/releases/tag/{{states('sensor.latest_version')}})

- alias: "System: Clear Upgrade Available Notification"
  id: system_clear_update_available_notification
  description: Clear notification of Home Assistant update available
  trigger:
    - platform: homeassistant
      event: start
  condition:
    - condition: template
      value_template: >
        {{ states('sensor.latest_version') == states('sensor.current_version') }}
  action:
    - service: persistent_notification.dismiss
      data:
        notification_id: update_pending

##########################
## Gasprice notifications
##########################
- id: diesel_price_changed
  alias: "Notification: Diesel price changed"
  trigger:
    - platform: state
      entity_id: sensor.diesel_u
  condition:
    - alias: "Check if price really changed"
      condition: template
      value_template: "{{ trigger.to_state.state != trigger.from_state.state }}"
  action:
    - service: notify.mobile_app_sm_a526b
      data:
        title: >-
          {% if trigger.to_state.state < trigger.from_state.state %}
          Diesel wordt goedkoper
          {% else %}
          Diesel wordt duurder
          {% endif %}
        message: >-
          {% if trigger.to_state.state < trigger.from_state.state %}
          ⛽ De dieselprijs is gezakt. 
          {% else %}
          ⛽ De dieselprijs is gestegen. 
          {% endif %}
          Nieuwe prijs: {{ trigger.to_state.state }}. 
          Oude prijs: {{ trigger.from_state.state }}.
        data:
          tag: diesel
          channel: diesel
