##########################
## Update Waze sensors during commute
##########################
- id: waze_update_commute
  alias: "Waze: update commute"
  initial_state: off #Off during COVID-19
  trigger:
    - platform: time_pattern
      minutes: "/5"
      seconds: 00
    - platform: homeassistant
      event: start
  condition:
    - condition: and
      conditions:
        - condition: time
          weekday:
            - mon
            - tue
            - wed
            - thu
            - fri
        - condition: or
          conditions:
            - condition: time
              after: "05:30:00"
              before: "08:00:00"
            - condition: time
              after: "15:00:00"
              before: "19:00:00"
  action:
    - choose:
        - conditions:
            condition: time
            after: "05:30:00"
            before: "08:00:00"
          sequence:
            service: homeassistant.update_entity
            entity_id: sensor.reistijd_thuis_werk
        - conditions:
            condition: time
            after: "15:00:00"
            before: "19:00:00"
          sequence:
            service: homeassistant.update_entity
            entity_id: sensor.reistijd_werk_thuis

- id: waze_update_to_home
  alias: "Waze: update to home"
  initial_state: on
  trigger:
    - platform: time_pattern
      minutes: "/5"
      seconds: 00
    - platform: homeassistant
      event: start
  condition:
    condition: state
    entity_id: person.bob
    state: not_home
  action:
    - service: homeassistant.update_entity
      entity_id: sensor.reistijd_bob_naar_huis

- alias: "System: Upgrade Available Notification"
  id: system_update_available_notification
  description: Send notification on Home Assistant update available
  trigger:
    - platform: state
      entity_id: sensor.latest_version
  condition:
    - condition: template
      value: >
        {{ states('sensor.latest_version') != states('sensor.current_version') }}
  action:
    - service: notify.mobile_app_sm_a505fn
      data:
        title: Upgrade time!
        message: >
          There is an upgrade for Home Assistant container pending!
          Version {{ states('sensor.latest_version') }} just got released!
        data:
          tag: System
          channel: System
          actions:
            - action: "URI"
              title: "Open Changelog"
              uri: "https://github.com/home-assistant/core/releases/tag/{{states('sensor.latest_version')}}"
