##########################
## UV Warnings
##########################
- alias: "UV: Melding"
  id: melding_uv
  initial_state: true
  trigger:
    platform: time
    at: input_datetime.time_uv_warning
  condition:
    - condition: state
      entity_id: input_boolean.notify_uv
      state: "on"
    - condition: template
      value_template: "{{ states('sensor.dark_sky_uv_index_0d') | float > 6.1 }}"
  action:
    - choose:
        - conditions:
            - condition: time
              weekday:
                - sat
                - sun
          sequence:
            - delay: "00:30:00" # Run at 08:30 in weekends
    - service: notify.mobile_devices
      data:
        title: "UV Waarschuwing"
        message: "Vandaag wordt zonkracht {{ states('sensor.dark_sky_uv_index_0d') }} verwacht. Vergeet niet te smeren!"
        data:
          tag: "notification-uv"
    - condition: state
      entity_id: input_boolean.notify_uv_voice
      state: "on"
    - service: tts.microsoft_say
      entity_id: media_player.woonkamer
      data:
        message: "Vandaag wordt zonkracht {{ states('sensor.dark_sky_uv_index_0d')  }} verwacht. Goed insmeren dus!"
    - delay: "00:00:04"
    - wait_template: "{{ is_state('media_player.woonkamer', 'idle') }}" # Ensure Home Hub screen is back to photo mode
    - service: media_player.turn_off
      entity_id: media_player.woonkamer
