##########################
## Schedule
##########################
- alias: "Vacuum: Ask to have Rocky do its cleaning"
  id: vacuum_ask_to_run
  initial_state: "on"
  variables:
    notification_service: >
      {% if is_state("device_tracker.moto_g_8_plus", "home") and is_state("device_tracker.sm_a526b", "home") %}notify.mobile_devices_adults
      {% elif is_state("device_tracker.moto_g_8_plus", "home") %}notify.mobile_app_moto_g_8_plus
      {% elif is_state("device_tracker.sm_a526b", "home") %}notify.mobile_app_sm_a526b
      {% else %}notify.bogus
      {% endif %}
  trigger:
    - platform: time
      at: "09:00"
    - platform: time
      at: "19:00"
  condition: "{{ as_timestamp(now()) - as_timestamp(states('sensor.vacuum_clean_start_time')) > 86400 }}"
  action:
    - alias: "Vraag of Rocky een rondje moet doen"
      service: "{{ notification_service }}"
      data:
        message: "Het is langer dan 24u geleden dat ik mijn laatste rondje heb gedaan. Zal ik gaan stofzuigen?"
        title: "Rocky"
        data:
          tag: vacuum
          channel: vacuum
          actions:
            - action: "vacuum_start_yes"
              title: "Ja, graag!"
            - action: "vacuum_start_no"
              title: "Nee, dank je."
          ttl: 0
          priority: high
    - alias: "Wacht op antwoord..."
      wait_for_trigger:
        - platform: event
          event_type: mobile_app_notification_action
          event_data:
            action: "vacuum_start_yes"
      timeout: "01:00:00"
      continue_on_timeout: false
    - alias: "Start Rocky na bevestiging"
      service: vacuum.start
      target:
        entity_id: vacuum.roborock_vacuum_s5e

##########################
## Notifications
##########################
- alias: "Vacuum: Rocky started cleaning"
  id: vacuum_notification_cleaning_started
  initial_state: "on"
  trigger:
    - platform: state
      entity_id: vacuum.roborock_vacuum_s5e
      from: "docked"
      to: "cleaning"
  action:
    - service: notify.mobile_app_sm_a526b
      data:
        title: "Rocky"
        message: "Rocky doet zijn rondje!"

- alias: "Vacuum: Fire Rocky stopped cleaning event"
  id: vacuum_event_cleaning_stopped
  initial_state: "on"
  trigger:
    - platform: state
      entity_id: vacuum.roborock_vacuum_s5e
      from: "returning"
      to: "docked"
  action:
    - alias: "Cleaning done - fire an event we listen to in other automations"
      event: vacuum_cleaning_ended

- alias: "Vacuum: Notify that Rocky stopped cleaning"
  id: vacuum_notification_stopped_and_docked
  initial_state: "on"
  trigger:
    - platform: event
      event_type: vacuum_cleaning_ended
  action:
    - alias: "Checking if this is the 3rd time cleaning..."
      choose:
        - conditions: "{{ (state_attr('vacuum.roborock_vacuum_s5e', 'cleaning_count') % 3) | int == 0 }}"
          sequence:
            - service: notify.mobile_app_sm_a526b
              data:
                message: "Rocky moet geleegd worden, hij was na {{state_attr('vacuum.roborock_vacuum_s5e','cleaning_time')}} minuten klaar met zijn werk!"
                title: "Rocky"
      default:
        - service: notify.mobile_app_sm_a526b
          data:
            title: "Rocky"
            message: "Rocky is na {{state_attr('vacuum.roborock_vacuum_s5e','cleaning_time')}} minuten klaar met zijn werk!."

##########################
## Maintenance notifications
##########################
- alias: "Vacuum: Notify that Rocky's sensors need maintenance"
  id: vacuum_notification_maintenance_sensors
  initial_state: "on"
  trigger:
    - platform: event
      event_type: vacuum_cleaning_ended
  condition:
    - alias: "Check for sensor status"
      condition: numeric_state
      entity_id: sensor.vacuum_sensor_dirty_left
      below: 2
  action:
    - service: notify.mobile_app_sm_a526b
      data:
        title: "Rocky needs maintenance"
        message: "De sensoren van Rocky moeten schoongemaakt worden. Resterende tijd: {{ states('sensor.vacuum_sensor_dirty_left')}} {{state_attr('sensor.vacuum_sensor_dirty_left','unit_of_measurement') }}."
        data:
          tag: vacuum
          channel: vacuum
          actions:
            - action: "vacuum_maintenance_sensors_done"
              title: "Onderhoud uitgevoerd!"
            - action: "vacuum_maintenance_sensors_later"
              title: "Nee, doe ik later"
          ttl: 0
          priority: high

- alias: "Vacuum: Notify that Rocky's main brush needs maintenance"
  id: vacuum_notification_maintenance_main_brush
  initial_state: "on"
  trigger:
    - platform: event
      event_type: vacuum_cleaning_ended
  condition:
    - alias: "Check for main brush status"
      condition: numeric_state
      entity_id: sensor.vacuum_main_brush_left
      below: 5
  action:
    - service: notify.mobile_app_sm_a526b
      data:
        title: "Rocky needs maintenance"
        message: "De hoofdborstel van Rocky moet bijna vervangen worden. Resterende tijd: {{ states('sensor.vacuum_main_brush_left')}} {{state_attr('sensor.vacuum_main_brush_left','unit_of_measurement') }}."
        data:
          tag: vacuum_maintenance
          channel: vacuum
          actions:
            - action: "vacuum_maintenance_main_brush_done"
              title: "Onderhoud uitgevoerd!"
            - action: "vacuum_maintenance_main_brush_later"
              title: "Nee, doe ik later"
          ttl: 0
          priority: high

- alias: "Vacuum: Notify that Rocky's side brush needs maintenance"
  id: vacuum_notification_maintenance_side_brush
  initial_state: "on"
  trigger:
    - platform: event
      event_type: vacuum_cleaning_ended
  condition:
    - alias: "Check for side brush status"
      condition: numeric_state
      entity_id: sensor.vacuum_side_brush_left
      below: 5
  action:
    - service: notify.mobile_app_sm_a526b
      data:
        title: "Rocky needs maintenance"
        message: "De zijborstel van Rocky moet bijna vervangen worden. Resterende tijd: {{ states('sensor.vacuum_side_brush_left')}} {{state_attr('sensor.vacuum_side_brush_left','unit_of_measurement') }}."
        data:
          tag: vacuum_maintenance
          channel: vacuum
          actions:
            - action: "vacuum_maintenance_side_brush_done"
              title: "Onderhoud uitgevoerd!"
            - action: "vacuum_maintenance_side_brush_later"
              title: "Nee, doe ik later"
          ttl: 0
          priority: high

- alias: "Vacuum: Notify that Rocky's filter needs maintenance"
  id: vacuum_notification_maintenance_filter
  initial_state: "on"
  trigger:
    - platform: event
      event_type: vacuum_cleaning_ended
  condition:
    - alias: "Check for filter status"
      condition: numeric_state
      entity_id: sensor.vacuum_filter_left
      below: 5
  action:
    - service: notify.mobile_app_sm_a526b
      data:
        title: "Rocky needs maintenance"
        message: "De filter van Rocky moet bijna vervangen worden. Resterende tijd: {{ states('sensor.vacuum_filter_left')}} {{state_attr('sensor.vacuum_filter_left','unit_of_measurement') }}."
        data:
          tag: vacuum_maintenance
          channel: vacuum
          actions:
            - action: "vacuum_maintenance_filter_done"
              title: "Onderhoud uitgevoerd!"
            - action: "vacuum_maintenance_filter_later"
              title: "Nee, doe ik later"
          ttl: 0
          priority: high

##########################
## Maintenance actions
##########################
- alias: "Vacuum: Reset Rocky's sensors maintenance interval"
  id: vacuum_reset_maintenance_sensors
  initial_state: "on"
  trigger:
    - platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: "vacuum_maintenance_sensors_done"
  action:
    - service: vacuum.send_Command
      alias: "Reset hours for sensor cleaning"
      target:
        entity_id: vacuum.roborock_vacuum_s5e
      data:
        command: reset_consumable
        params: ["sensor_dirty_time"]
    - service: notify.mobile_app_sm_a526b
      data:
        title: "Maintenance completed"
        message: "De sensortijd is gereset. Resterende tijd: {{ states('sensor.vacuum_sensor_dirty_left')}} {{state_attr('sensor.vacuum_sensor_dirty_left','unit_of_measurement') }}."
        data:
          tag: vacuum_maintenance
          channel: vacuum
          ttl: 0
          priority: high

- alias: "Vacuum: Reset Rocky's main brush maintenance interval"
  id: vacuum_reset_maintenance_main_brush
  initial_state: "on"
  trigger:
    - platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: "vacuum_maintenance_main_brush_done"
  action:
    - service: vacuum.send_Command
      alias: "Reset hours for main brush replacement"
      target:
        entity_id: vacuum.roborock_vacuum_s5e
      data:
        command: reset_consumable
        params: ["main_brush_work_time"]
    - service: notify.mobile_app_sm_a526b
      data:
        title: "Maintenance completed"
        message: "De hoofdborstel van Rocky is vervangen. Resterende tijd: {{ states('sensor.vacuum_main_brush_left')}} {{state_attr('sensor.vacuum_main_brush_left','unit_of_measurement') }}."
        data:
          tag: vacuum_maintenance
          channel: vacuum
          ttl: 0
          priority: high

- alias: "Vacuum: Reset Rocky's side brush maintenance interval"
  id: vacuum_reset_maintenance_side_brush
  initial_state: "on"
  trigger:
    - platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: "vacuum_maintenance_side_brush_done"
  action:
    - service: vacuum.send_Command
      alias: "Reset hours for side brush replacement"
      target:
        entity_id: vacuum.roborock_vacuum_s5e
      data:
        command: reset_consumable
        params: ["side_brush_work_time"]
    - service: notify.mobile_app_sm_a526b
      data:
        title: "Maintenance completed"
        message: "De zijborstel van Rocky is vervangen. Resterende tijd: {{ states('sensor.vacuum_side_brush_left')}} {{state_attr('sensor.vacuum_side_brush_left','unit_of_measurement') }}."
        data:
          tag: vacuum_maintenance
          channel: vacuum
          ttl: 0
          priority: high

- alias: "Vacuum: Reset Rocky's filter maintenance interval"
  id: vacuum_reset_maintenance_filter
  initial_state: "on"
  trigger:
    - platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: "vacuum_maintenance_filter_done"
  action:
    - service: vacuum.send_Command
      alias: "Reset hours for filter replacement"
      target:
        entity_id: vacuum.roborock_vacuum_s5e
      data:
        command: reset_consumable
        params: ["filter_work_time"]
    - service: notify.mobile_app_sm_a526b
      data:
        title: "Maintenance completed"
        message: "De filter van Rocky is vervangen. Resterende tijd: {{ states('sensor.vacuum_filter_left')}} {{state_attr('sensor.vacuum_filter_left','unit_of_measurement') }}."
        data:
          tag: vacuum_maintenance
          channel: vacuum
          ttl: 0
          priority: high

##########################
## Capture errors
##########################
- alias: "Vacuum: Rocky is in error mode"
  id: vacuum_notification_error
  initial_state: "on"
  trigger:
    - platform: state
      entity_id: sensor.vacuum_error_status
  condition:
    - condition: not
      conditions:
        condition: state
        entity_id: sensor.vacuum_error_status
        state: "unknown"
  action:
    - service: notify.mobile_app_sm_a526b
      data:
        title: "Rocky"
        message: "Rocky heeft een probleem: {{state('sensor.vacuum_error_status')}}"

##########################
## Disable vacuum camera when docked
##########################
- alias: "Vacuum: camera on/off"
  id: vacuum_camera_onoff
  initial_state: true
  mode: restart
  trigger:
    - platform: state
      entity_id: vacuum.roborock_vacuum_s5e
    - platform: homeassistant
      event: start
  action:
    - service:
        "{% if states('vacuum.roborock_vacuum_s5e') in ['unavailable', 'unknown', 'docked'] %}
        camera.turn_off
        {% else %}
        camera.turn_on
        {% endif %}"
      entity_id: camera.stofzuiger
