##########################
## Washing machine alerts
##########################

# Turn on helper if washing machine starts
- alias: "Wasmachine draait"
  id: helper_wasmachine
  initial_state: true
  trigger:
    # High power: someone started the washing program...
    platform: numeric_state
    entity_id: sensor.wasmachine_power
    above: 1500
  condition:
    - condition: state
      entity_id: input_boolean.wasmachine_actief
      state: "off"
  action:
    # We know the washing machine is on: set helper
    - service: homeassistant.turn_on
      entity_id: input_boolean.wasmachine_actief

# Notify us when washing is done
- alias: "Wasmachine klaar melding"
  id: melding_wasmachine
  initial_state: true
  trigger:
    # Low power state for over a minute: washing done
    platform: numeric_state
    entity_id: sensor.wasmachine_power
    below: 5
    for:
      minutes: 1
  condition:
    # Only if we know that the washing machine is running
    - condition: state
      entity_id: input_boolean.wasmachine_actief
      state: "on"
  action:
    # Play a TTS alert downstairs
    - service: notify.tts_woonkamer
      data:
        message: "De wasmachine is klaar."
    # Turn off helper boolean: machine not active anymore
    - service: homeassistant.turn_off
      entity_id: input_boolean.wasmachine_actief
    # Show image as visual reminder washing is done
    - delay: "00:00:10" # Wait for TTS to finish
    - service: media_player.play_media
      data:
        entity_id: media_player.woonkamer
        media_content_id: !secret image_url_wasmachine
        media_content_type: "image/png"
    - delay: "00:15:00"
    - service: media_player.turn_off
      entity_id:
        - media_player.woonkamer

# Turn of reminder light
- alias: "Wasmachine: zet LED uit"
  id: wasmachine_LED_uit
  initial_state: true
  trigger:
    # If the machine is turned off
    - platform: numeric_state
      entity_id: sensor.wasmachine_power
      below: 1
    # Or, if a new cycle is started without turning off
    - platform: numeric_state
      entity_id: sensor.wasmachine_power
      above: 1500
    # Or, if we forgot about it or something went wrong
    - platform: time
      at: "23:59:00"
  action:
    # Stop casting image to Google Home
    - service: media_player.turn_off
      entity_id:
        - media_player.woonkamer
