##########################
## Zigbee2mqtt
##########################
# Sensor for monitoring the bridge state
- platform: mqtt
  name: Zigbee2mqtt Bridge
  state_topic: "zigbee2mqtt/bridge/state"
  payload_on: "online"
  payload_off: "offline"
  availability_topic: "zigbee2mqtt/bridge/state"
  payload_available: "online"
  payload_not_available: "offline"
  device_class: connectivity

##########################
## GPIO on Raspberry Pi
##########################
- platform: rpi_gpio
  ports:
    17: Doorbell
  pull_mode: "UP"
  invert_logic: true
