##########################
## Zigbee2mqtt
##########################
# Sensor for monitoring the bridge state
- platform: mqtt
  unique_id: zigbee2mqtt_bridge
  name: Zigbee2mqtt Bridge
  state_topic: "zigbee2mqtt/bridge/state"
  payload_on: "online"
  payload_off: "offline"
  availability_topic: "zigbee2mqtt/bridge/state"
  payload_available: "online"
  payload_not_available: "offline"
  device_class: connectivity

##########################
## Template sensors
##########################
- platform: template
  sensors:
    ## UV Warning
    uv_index_warning_level:
      friendly_name: "UV above warning level"
      value_template: "{{ states('sensor.dark_sky_uv_index')| float > 5.9 }}"
    ## Front door alert
    alert_front_door:
      friendly_name: "Front door alert status"
      value_template: >-
        {{ is_state('binary_sensor.door_sensor_2_contact', 'on')
            and is_state('input_boolean.notify_door_alert', 'on') }}
    ## Freezer door alert
    alert_freezer_door:
      friendly_name: "Freezer door alert status"
      value_template: >-
        {{ is_state('binary_sensor.door_sensor_1_contact', 'on')
            and is_state('input_boolean.notify_door_alert', 'on') }}

##########################
## Schoolday sensor
##########################
- platform: workday
  name: "Schooldag"
  country: NL
  add_holidays: !include ./holidays.yaml
