##########################
## Zigbee2mqtt
##########################
# Sensor for monitoring the bridge state
- platform: mqtt
  name: Zigbee2mqtt Bridge
  state_topic: "zigbee2mqtt/bridge/state"
  payload_on: "online"
  payload_off: "offline"
  availability_topic: "zigbee2mqtt/bridge/state"
  payload_available: "online"
  payload_not_available: "offline"
  device_class: connectivity

##########################
## GPIO on Raspberry Pi
##########################
- platform: rpi_gpio
  ports:
    17: Doorbell
  pull_mode: "UP"
  invert_logic: true

##########################
## UV Warning
##########################
- platform: template
  sensors:
    uv_index_warning_level:
      entity_id: sensor.dark_sky_uv_index
      friendly_name: 'UV above warning level'
      value_template: "{{ states('sensor.dark_sky_uv_index')| float > 5.9 }}"