##########################
## Connectivity sensor
##########################
- platform: group
  name: Statussen
  device_class: connectivity
  all: true
  entities:
    - binary_sensor.hp_printer_connectivity
    - binary_sensor.kast_status
    - binary_sensor.overkapping_status
    - binary_sensor.staande_lamp_status
    - binary_sensor.weerhuisje_status
    - binary_sensor.zigbee2mqtt_bridge
    - binary_sensor.zoutlamp_status
