##########################
## Connectivity sensor
##########################
- platform: group
  name: Statussen
  device_class: connectivity
  all: true
  entities:
    - binary_sensor.deurbel_status
    - binary_sensor.kast_status
    - binary_sensor.overkapping_status
    - binary_sensor.staande_lamp_status
    - binary_sensor.weerhuisje_status
    - binary_sensor.zigbee2mqtt_bridge
    - binary_sensor.zoutlamp_status

##########################
## Schoolday sensor
##########################
- platform: workday
  name: "Schooldag"
  country: NL
  remove_holidays:
    - "Goede Vrijdag"
  add_holidays: !include ./holidays.yaml
