#############################
## Notify Group all mobiles #
#############################
- platform: group
  name: mobile_devices_adults
  services:
    - service: mobile_app_sm_a526b
    - service: mobile_app_moto_g_8_plus

- platform: group
  name: mobile_devices_all
  services:
    - service: mobile_app_sm_a526b
    - service: mobile_app_moto_g_8_plus
    - service: mobile_app_schaduwspeler

#############################
## Notify AndroidTV         #
#############################
- platform: nfandroidtv
  name: TV
  host: !secret cast_ip_androidtv

#############################
## Notify Google TTS        #
#############################
- platform: tts
  name: tts_woonkamer
  tts_service: tts.microsoft_say
  media_player: media_player.woonkamer

- platform: tts
  name: tts_hele_huis
  tts_service: tts.microsoft_say
  media_player: media_player.hele_huis

#############################
## Notify bogus service     #
#############################
# Used to let automations not error out
- name: bogus
  platform: command_line
  command: ""
