##########################
## History statistics
##########################
- platform: history_stats
  name: Pubercave ON today
  entity_id: binary_sensor.is_pubercave_on
  state: "on"
  type: time
  start: "{{ now().replace(hour=0, minute=0, second=0) }}"
  end: "{{ now() }}"
- platform: history_stats
  name: Minicave ON today
  entity_id: binary_sensor.is_minicave_on
  state: "on"
  type: time
  start: "{{ now().replace(hour=0, minute=0, second=0) }}"
  end: "{{ now() }}"

##########################
## System sensors
##########################
- platform: systemmonitor
  resources:
    - type: memory_use
    - type: memory_use_percent
    - type: processor_use

##########################
## Weather sensors
##########################
- platform: darksky
  api_key: !secret darksky_api
  forecast:
    - 0
    - 1
    - 2
  hourly_forecast:
    - 0
    - 1
    - 2
    - 3
  monitored_conditions:
    - cloud_cover
    - summary
    - temperature_high
    - uv_index
  scan_interval:
    minutes: 15
  language: nl
