##########################
## System sensors
##########################
- platform: version
- platform: version
  source: docker

- platform: systemmonitor
  resources:
    - type: memory_use
    - type: memory_use_percent
    - type: processor_use

##########################
## Weather sensors
##########################
- platform: darksky
  api_key: !secret darksky_api
  forecast:
    - 0
    - 1
    - 2
  hourly_forecast:
    - 0
    - 1
    - 2
    - 3
  monitored_conditions:
    - cloud_cover
    - summary
    - temperature_high
    - uv_index
  scan_interval:
    minutes: 15
  language: nl

##########################
## Gas prices sensors
##
## Just scraping the Tinq website pages for the needed information
## URLs are to their site: https://www.tinq.nl/tankstations/utrecht-atoomweg (random example)
## Using !secret as to somewhat keep some privacy for the exact locations I scrape.
##########################
- platform: scrape
  resource: !secret scrape_url_z
  name: "Diesel Z"
  select: ".field--name-field-station-prices .taxonomy-term-Diesel .field--name-field-prices-price-pump"
  value_template: "{{ value | replace('€', '') | replace('EUR/L', '') | float | round(3) }}"
  unit_of_measurement: €
  scan_interval: 3600

- platform: scrape
  resource: !secret scrape_url_z
  name: "Benzine Z"
  select: ".field--name-field-station-prices .taxonomy-term-Euro95 .field--name-field-prices-price-pump"
  value_template: "{{ value | replace('€', '') | replace('EUR/L', '') | float | round(3) }}"
  unit_of_measurement: €
  scan_interval: 3600

- platform: scrape
  resource: !secret scrape_url_u
  name: "Diesel U"
  select: ".field--name-field-station-prices .taxonomy-term-Diesel .field--name-field-prices-price-pump"
  value_template: "{{ value | replace('€', '') | replace('EUR/L', '') | float | round(3) }}"
  unit_of_measurement: €
  scan_interval: 3600

- platform: scrape
  resource: !secret scrape_url_u
  name: "Benzine U"
  select: ".field--name-field-station-prices .taxonomy-term-Euro95 .field--name-field-prices-price-pump"
  value_template: "{{ value | replace('€', '') | replace('EUR/L', '') | float | round(3) }}"
  unit_of_measurement: €
  scan_interval: 3600

##########################
## Trash sensors
##########################
- platform: afvalinfo
  resources:
    - gft
    - papier
    - pbd
    - restafval
    - trash_type_today
    - trash_type_tomorrow
  location: !secret afvalinfo_location
  postcode: !secret afvalinfo_postcode
  streetnumber: !secret afvalinfo_streetnumber
  locale: "nl"

##########################
## Smartmeter sensors
##########################
- platform: dsmr_reader

##########################
## Quote of the day sensor
##########################
- platform: rest
  resource: https://quotes.rest/qod?language=en
  name: Quote of the Day
  scan_interval: 43200
  json_attributes_path: "$.contents.quotes[0]"
  json_attributes:
    - author
    - category
    - quote
  value_template: "OK"
