##########################
## History statistics
##########################
- platform: history_stats
  name: Pubercave ON today
  entity_id: binary_sensor.is_pubercave_on
  state: "on"
  type: time
  start: "{{ now().replace(hour=0, minute=0, second=0) }}"
  end: "{{ now() }}"
- platform: history_stats
  name: Minicave ON today
  entity_id: binary_sensor.is_minicave_on
  state: "on"
  type: time
  start: "{{ now().replace(hour=0, minute=0, second=0) }}"
  end: "{{ now() }}"

##########################
## System sensors
##########################
- platform: systemmonitor
  resources:
    - type: memory_use
    - type: memory_use_percent
    - type: processor_use

- platform: tgtg
  username: !secret tgtg_username
  access_token: !secret tgtg_access_token
  refresh_token: !secret tgtg_refresh_token
  user_id: !secret tgtg_user_id
  scan_interval: 300

##########################
## Trash sensors
##########################
- platform: afvalinfo
  resources:
    - gft
    - papier
    - pbd
    - restafval
    - trash_type_today
    - trash_type_tomorrow
  location: !secret afvalinfo_location
  postcode: !secret afvalinfo_postcode
  streetnumber: !secret afvalinfo_streetnumber
  locale: "nl"
- platform: afvalinfo
  id: nieuwe-huis
  resources:
    - gft
    - papier
    - pbd
    - restafval
    - trash_type_today
    - trash_type_tomorrow
  location: !secret afvalinfo_location
  postcode: !secret afvalinfo_postcode_2
  streetnumber: !secret afvalinfo_streetnumber_2
  locale: "nl"

##########################
## Weather sensors
##########################
- platform: darksky
  api_key: !secret darksky_api
  forecast:
    - 0
    - 1
    - 2
  hourly_forecast:
    - 0
    - 1
    - 2
    - 3
  monitored_conditions:
    - cloud_cover
    - summary
    - temperature_high
    - uv_index
  scan_interval:
    minutes: 15
  language: nl

##########################
## Dynamic energy prices
##########################
- platform: nordpool
  region: "NL"
  currency: "EUR"
  VAT: False
  precision: 3
  low_price_cutoff: 0.9
  price_in_cents: false
  price_type: kWh
  additional_costs: >
    {% set VAT = 0.21 %}
    {% set tax_kWh = 0.12599 %}
    {% set opslag = 0.0025 %}
    {{ ((current_price * VAT ) + (tax_kWh + opslag) * (1 + VAT)) | float }}

##########################
## Formula 1
##########################
- platform: formulaone_api
