##########################
## System sensors
##########################
- platform: systemmonitor
  resources:
    - type: memory_use
    - type: memory_use_percent
    - type: processor_use

##########################
## Weather sensors
##########################
- platform: darksky
  api_key: !secret darksky_api
  forecast:
    - 0
    - 1
    - 2
  hourly_forecast:
    - 0
    - 1
    - 2
    - 3
  monitored_conditions:
    - cloud_cover
    - summary
    - temperature_high
    - uv_index
  scan_interval:
    minutes: 15
  language: nl
