##########################
## System sensors
##########################
- platform: version
  name: HA Currently Installed

##########################
## Utility sensors
##########################

- platform: template
  sensors:
    batterij_pir:
      entity_id: zwave.pir
      friendly_name: 'PIR Batterij' 
      value_template: >
          {%- if states.zwave.pir.attributes.battery_level %}
              {{ state_attr('zwave.pir', 'battery_level') | round }}
          {% else %}
              "0"
          {%- endif %}
      unit_of_measurement: '%'
      icon_template: >
          {%- if states.zwave.pir.attributes.battery_level is defined %}
             {% set battery_level = states.zwave.pir.attributes.battery_level|int %}
             {% set battery_round = (battery_level / 10) |int * 10 %}
             {% if battery_round >= 100 %}
               mdi:battery
             {% elif battery_round > 0 %}
               mdi:battery-{{ battery_round }}
             {% else %}
              mdi:battery-alert
             {% endif %}
          {% else %}
              mdi:battery-alert
          {% endif %}
    outside_temperature:
      entity_id: weather.dark_sky
      friendly_name: 'Buitentemperatuur'
      unit_of_measurement: '°C'
      value_template: >
          {%- if states.weather.dark_sky.attributes.temperature is defined %}
              {{ states.weather.dark_sky.attributes.temperature }}
          {% else %}
              0
          {%- endif %}
    room_temperature:
      entity_id: climate.woonkamer
      friendly_name: 'Kamertemperatuur'
      unit_of_measurement: '°C'
      value_template: >
          {%- if states.climate.woonkamer.attributes.current_temperature is defined %}
              {{ states.climate.woonkamer.attributes.current_temperature }}
          {% else %}
              0
          {%- endif %}

##########################
## Toon sensors
##########################
- platform: toon_smartmeter
  host: !secret toon_host
  port: !secret toon_port
  scan_interval: 15
  resources:
#    - gasused
#    - gasusedcnt
    - elecusageflowlow
    - elecusagecntlow
    - elecusageflowhigh
    - elecusagecnthigh

##########################
## Waze sensors
##########################
- platform: waze_travel_time
  name: Reistijd Bob naar huis
  origin: device_tracker.bob_a50
  destination: zone.home
  region: 'EU'
  scan_interval: 1800

- platform: waze_travel_time
  name: Reistijd Thuis-Werk
  origin: zone.home
  destination: zone.work
  region: 'EU'
  scan_interval: 1800

- platform: waze_travel_time
  name: Reistijd Werk-Thuis
  origin: zone.work
  destination: zone.home
  region: 'EU'
  scan_interval: 1800

##########################
## Geocode
##########################
- platform: google_geocode
  origin: device_tracker.bob_a50
  options: street, city
  display_zone: show
  api_key: !secret google_maps_api_key
  scan_interval: 300

##########################
## Gas prices sensors
##########################
- platform: scrape
  resource: !secret scrape_url_z
  name: 'Diesel Z'
  select: ".field--name-field-station-prices .taxonomy-term-Diesel .field--name-field-prices-price-pump"
  value_template: "{{ value | replace('€', '') | replace('EUR/L', '') | float | round(3) }}"
  unit_of_measurement: €
  scan_interval: 3600

- platform: scrape
  resource: !secret scrape_url_z
  name: 'Benzine Z'
  select: ".field--name-field-station-prices .taxonomy-term-Euro95 .field--name-field-prices-price-pump"
  value_template: "{{ value | replace('€', '') | replace('EUR/L', '') | float | round(3) }}"
  unit_of_measurement: €
  scan_interval: 3600

- platform: scrape
  resource: !secret scrape_url_u
  name: 'Diesel U'
  select: ".field--name-field-station-prices .taxonomy-term-Diesel .field--name-field-prices-price-pump"
  value_template: "{{ value | replace('€', '') | replace('EUR/L', '') | float | round(3) }}"
  unit_of_measurement: €
  scan_interval: 3600

- platform: scrape
  resource: !secret scrape_url_u
  name: 'Benzine U'
  select: ".field--name-field-station-prices .taxonomy-term-Euro95 .field--name-field-prices-price-pump"
  value_template: "{{ value | replace('€', '') | replace('EUR/L', '') | float | round(3) }}"
  unit_of_measurement: €
  scan_interval: 3600

##########################
## Trash sensors
##########################
- platform: rest
  resource: !secret scrape_url_afval
  name: Trash_Today
  scan_interval: 3600
  value_template: >
    {% set now = as_timestamp(now()) %}
    {% set today = now | timestamp_custom("%d/%m/%Y") %}
    {% set containerType = value_json.days[ today ] %}
    {% if containerType | trim != "" %}
      {% set trash = value_json.legend[ containerType ] %}
      {{ trash }}
    {% else %}
      Geen
    {% endif %}
- platform: rest
  resource: !secret scrape_url_afval
  name: Trash_Tomorrow
  scan_interval: 3600
  value_template: >
    {% set now = as_timestamp(now()) %}
    {% set oneDay = 86400 %}
    {% set nextDay = now + oneDay %}
    {% set tomorrow = nextDay | timestamp_custom("%d/%m/%Y") %}
    {% set containerType = value_json.days[ tomorrow ] %}
    {% if containerType | trim != "" %}
      {% set trash = value_json.legend[ containerType ] %}
      {{ trash }}
    {% else %}
      Geen
    {% endif %}

##########################
## BT Detection
##########################

### Bob ###    
- platform: mqtt
  name: 'BT Beneden Bob'
  state_topic: 'location/beneden/hmmbob'
  value_template: '{{ value_json.confidence }}'
  unit_of_measurement: '%'
  json_attributes_topic: 'location/beneden/hmmbob'

- platform: mqtt
  name: 'BT Boven Bob'
  state_topic: 'location/boven/hmmbob'
  value_template: '{{ value_json.confidence }}'
  unit_of_measurement: '%'
  json_attributes_topic: 'location/boven/hmmbob'

- platform: min_max
  name: "BT max Bob"
  type: max
  round_digits: 0
  entity_ids:
    - sensor.bt_boven_bob
    - sensor.bt_beneden_bob

### Birgit ###
- platform: mqtt
  state_topic: 'location/beneden/bridget_jones_moto'
  value_template: '{{ value_json.confidence }}'
  unit_of_measurement: '%'
  name: 'BT Beneden Birgit'
  json_attributes_topic: 'location/beneden/bridget_jones_moto'

- platform: mqtt
  state_topic: 'location/boven/bridget_jones_moto'
  value_template: '{{ value_json.confidence }}'
  unit_of_measurement: '%'
  name: 'BT Boven Birgit'
  json_attributes_topic: 'location/boven/bridget_jones_moto'

- platform: min_max
  name: "BT max Birgit"
  type: max
  round_digits: 0
  entity_ids:
    - sensor.bt_boven_birgit
    - sensor.bt_beneden_birgit
