##########################
## System sensors
##########################
- platform: version
- platform: version
  source: docker

- platform: systemmonitor
  resources:
    - type: memory_use_percent
    - type: memory_use
    - type: processor_use

##########################
## Weather sensors
##########################
- platform: darksky
  api_key: !secret darksky_api
  forecast:
    - 0
    - 1
    - 2
  hourly_forecast:
    - 0
    - 1
    - 2
    - 3
  monitored_conditions:
    - cloud_cover
    - uv_index
  scan_interval:
    minutes: 15

- platform: template
  sensors:
    outside_temperature:
      friendly_name: "Buitentemperatuur"
      unit_of_measurement: "°C"
      value_template: >
        {%- if states.weather.dark_sky.attributes.temperature is defined %}
            {{ state_attr('weather.dark_sky', 'temperature') }}
        {% else %}
            0
        {%- endif %}
    outside_humidity:
      friendly_name: "Luchtvochtigheid"
      unit_of_measurement: "%"
      value_template: >
        {%- if states.weather.dark_sky.attributes.humidity is defined %}
            {{ state_attr('weather.dark_sky', 'humidity') }}
        {% else %}
            0
        {%- endif %}
    room_temperature:
      friendly_name: "Kamertemperatuur"
      unit_of_measurement: "°C"
      value_template: >
        {%- if states.climate.woonkamer.attributes.current_temperature is defined %}
            {{ state_attr('climate.woonkamer', 'current_temperature') }}
        {% else %}
            0
        {%- endif %}

##########################
## Toon sensors
##########################
- platform: toon_smartmeter
  host: !secret toon_host
  scan_interval: 15
  resources:
    - elecusageflowlow
    - elecusagecntlow
    - elecusageflowhigh
    - elecusagecnthigh
#    - gasused
#    - gasusedcnt

##########################
## Waze sensors
##########################
- platform: waze_travel_time
  name: Reistijd Bob naar huis
  origin: device_tracker.sm_a505fn
  destination: zone.home
  region: "EU"
  scan_interval: 1800

#- platform: waze_travel_time      ## Not being used in COVID-19 times,
#  name: Reistijd Thuis-Werk       ## commented out because I don't need the updates now
#  origin: zone.home
#  destination: zone.work
#  region: 'EU'
#  scan_interval: 1800
#
#- platform: waze_travel_time
#  name: Reistijd Werk-Thuis
#  origin: zone.work
#  destination: zone.home
#  region: 'EU'
#  scan_interval: 1800

##########################
## Gas prices sensors
##########################
- platform: scrape
  resource: !secret scrape_url_z
  name: "Diesel Z"
  select: ".field--name-field-station-prices .taxonomy-term-Diesel .field--name-field-prices-price-pump"
  value_template: "{{ value | replace('€', '') | replace('EUR/L', '') | float | round(3) }}"
  unit_of_measurement: €
  scan_interval: 3600

- platform: scrape
  resource: !secret scrape_url_z
  name: "Benzine Z"
  select: ".field--name-field-station-prices .taxonomy-term-Euro95 .field--name-field-prices-price-pump"
  value_template: "{{ value | replace('€', '') | replace('EUR/L', '') | float | round(3) }}"
  unit_of_measurement: €
  scan_interval: 3600

- platform: scrape
  resource: !secret scrape_url_u
  name: "Diesel U"
  select: ".field--name-field-station-prices .taxonomy-term-Diesel .field--name-field-prices-price-pump"
  value_template: "{{ value | replace('€', '') | replace('EUR/L', '') | float | round(3) }}"
  unit_of_measurement: €
  scan_interval: 3600

- platform: scrape
  resource: !secret scrape_url_u
  name: "Benzine U"
  select: ".field--name-field-station-prices .taxonomy-term-Euro95 .field--name-field-prices-price-pump"
  value_template: "{{ value | replace('€', '') | replace('EUR/L', '') | float | round(3) }}"
  unit_of_measurement: €
  scan_interval: 3600

##########################
## Trash sensors
##########################
- platform: rest
  resource: !secret scrape_url_afval
  name: Trash_Today
  scan_interval: 3600
  value_template: >
    {% set now = as_timestamp(now()) %}
    {% set today = now | timestamp_custom("%d/%m/%Y") %}
    {% set containerType = value_json.days[ today ] %}
    {% if containerType | trim != "" %}
      {% set trash = value_json.legend[ containerType ] %}
      {{ trash }}
    {% else %}
      Geen
    {% endif %}
- platform: rest
  resource: !secret scrape_url_afval
  name: Trash_Tomorrow
  scan_interval: 3600
  value_template: >
    {% set now = as_timestamp(now()) %}
    {% set oneDay = 86400 %}
    {% set nextDay = now + oneDay %}
    {% set tomorrow = nextDay | timestamp_custom("%d/%m/%Y") %}
    {% set containerType = value_json.days[ tomorrow ] %}
    {% if containerType | trim != "" %}
      {% set trash = value_json.legend[ containerType ] %}
      {{ trash }}
    {% else %}
      Geen
    {% endif %}
