##########################
## System sensors
##########################
- platform: systemmonitor
  resources:
    - type: memory_use
    - type: memory_use_percent
    - type: processor_use

- platform: sql
  db_url: !secret recorder_url
  queries:
    - name: Database Grootte
      query: 'SELECT table_schema "homeassistant", Round(Sum(data_length + index_length) / POWER(1024,2), 1) "value" FROM information_schema.tables WHERE table_schema="homeassistant" GROUP BY table_schema;'
      column: "value"
      unit_of_measurement: mB

##########################
## Weather sensors
##########################
- platform: darksky
  api_key: !secret darksky_api
  forecast:
    - 0
    - 1
    - 2
  hourly_forecast:
    - 0
    - 1
    - 2
    - 3
  monitored_conditions:
    - cloud_cover
    - summary
    - temperature_high
    - uv_index
  scan_interval:
    minutes: 15
  language: nl

##########################
## Gas prices sensors
##
## Just scraping the Tinq website pages for the needed information
## URLs are to their site: https://www.tinq.nl/tankstations/utrecht-atoomweg (random example)
## Using !secret as to somewhat keep some privacy for the exact locations I scrape.
##########################
- platform: scrape
  resource: !secret scrape_url_u
  name: "Diesel"
  select: ".field--name-field-station-prices .taxonomy-term-Diesel .field--name-field-prices-price-pump"
  value_template: "{{ value | replace('€', '') | replace('EUR/L', '') | float | round(3) }}"
  unit_of_measurement: €
  scan_interval: 3600

- platform: scrape
  resource: !secret scrape_url_u
  name: "Benzine"
  select: ".field--name-field-station-prices .taxonomy-term-Euro95 .field--name-field-prices-price-pump"
  value_template: "{{ value | replace('€', '') | replace('EUR/L', '') | float | round(3) }}"
  unit_of_measurement: €
  scan_interval: 3600

##########################
## Trash sensors
##########################
- platform: afvalinfo
  resources:
    - gft
    - papier
    - pbd
    - restafval
    - trash_type_today
    - trash_type_tomorrow
  location: !secret afvalinfo_location
  postcode: !secret afvalinfo_postcode
  streetnumber: !secret afvalinfo_streetnumber
  locale: "nl"

##########################
## Smartmeter sensors
##########################
- platform: dsmr_reader

##########################
## History statistics
##########################
- platform: history_stats
  name: Pubercave ON today
  entity_id: binary_sensor.is_pubercave_on
  state: "on"
  type: time
  start: "{{ now().replace(hour=0, minute=0, second=0) }}"
  end: "{{ now() }}"
