disable_movement_automations_package:
  input_boolean:
    disable_pir_sensor_automations:
      name: "Schakel bewegings-automatiseringen uit"
      icon: mdi:sofa-outline
  #automation:
  #  - id: disable_movement_automations
  #    alias: "System: Disable movement automations"
  #    trigger:
  #      - platform: state
  #        entity_id: input_boolean.disable_pir_sensor_automations
  #        from: "off"
  #        to: "on"
  #        id: "turn_off"
  #      - platform: state
  #        entity_id: input_boolean.disable_pir_sensor_automations
  #        from: "on"
  #        to: "off"
  #        id: "turn_on"
  #    action:
  #      - alias: "Toggling relevant input booleans"
  #        service: input_boolean.{{ trigger.id }}
  #        target:
  #          entity_id:
  #            - input_boolean.enable_pir_woonkamer_automations
  #            - input_boolean.enable_pir_gang_automations
  #            - input_boolean.toon_on_through_movement
